version: "3.9"
services:
  web:
    build: .
    command: bash -c "rm -f /app/tmp/pids/server.pid && bin/rails server -b 0.0.0.0 -p 3000"
    container_name: rails_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app:cached
    stdin_open: true
    tty: true
